# Generated by Django 5.1.6 on 2025-02-08 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('On-campus', 'On-campus'), ('Off-campus', 'Off-campus')], max_length=50)),
                ('hostel_type', models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Triple Room', 'Triple Room'), ('Quadruple Room', 'Quadruple Room'), ('Quintuple Room', 'Quintuple Room'), ('Sextuple Room', 'Sextuple Room')], max_length=50)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('available_spaces', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hostel')),
            ],
        ),
    ]
