# Generated by Django 5.1.6 on 2025-02-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hostel_type',
            field=models.CharField(blank=True, choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Triple Room', 'Triple Room'), ('Quadruple Room', 'Quadruple Room'), ('Quintuple Room', 'Quintuple Room'), ('Sextuple Room', 'Sextuple Room')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, choices=[('On-campus', 'On-campus'), ('Off-campus', 'Off-campus')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
