# Generated by Django 5.1.6 on 2025-02-26 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.CreateModel(
            name='HostelApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=50, unique=True)),
                ('year_of_study', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('hostel_type', models.CharField(choices=[('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Triple Room', 'Triple Room'), ('Quadruple Room', 'Quadruple Room'), ('Quintuple Room', 'Quintuple Room'), ('Sextuple Room', 'Sextuple Room')], max_length=20)),
                ('location', models.CharField(choices=[('On-campus', 'On-campus'), ('Off-campus', 'Off-campus')], max_length=10)),
                ('hostel_name', models.CharField(choices=[('Mfumbiro Hostel - (Male)', 'Mfumbiro Hostel - (Male)'), ('Nyandarua Hostel', 'Nyandarua Hostel'), ('Old Menengai Hostel - (Male)', 'Old Menengai Hostel - (Male)'), ('New Menengai 3,4,5 and 6 Hostel - (Male)', 'New Menengai 3,4,5 and 6 Hostel - (Male)'), ('New Ruwenzori Hostel - (Male)', 'New Ruwenzori Hostel - (Male)'), ('Usambara Hostel blocks 2,3,4 and 5-(Male)', 'Usambara Hostel blocks 2,3,4 and 5-(Male)'), ('Longonot Hostel-(Male)', 'Longonot Hostel-(Male)'), ('Kilimambogo Hostel-(Male)', 'Kilimambogo Hostel-(Male)'), ('Nyayo Three-(Male)', 'Nyayo Three-(Male)'), ('Nyayo Four-(Male)', 'Nyayo Four-(Male)'), ('New Menengai 1 and 2 Hostel - (Female)', 'New Menengai 1 and 2 Hostel - (Female)'), ('New Aberdares Hostel - (Female)', 'New Aberdares Hostel - (Female)'), ('Old Aberdares Hostel - (Female)', 'Old Aberdares Hostel - (Female)'), ('Ngong Hostel - (Female)', 'Ngong Hostel - (Female)'), ('Old Ruwenzori Hostel - (Female)', 'Old Ruwenzori Hostel - (Female)'), ('Usambara Hostel block 1 - (Female)', 'Usambara Hostel block 1 - (Female)'), ('Lukenya Hostel - (Female)', 'Lukenya Hostel - (Female)'), ('Nyayo One - (Female)', 'Nyayo One - (Female)'), ('Nyayo Two - (Female)', 'Nyayo Two - (Female)')], max_length=100)),
                ('cost_per_semester', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Allocated', 'Allocated')], default='Pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
